version: '3'
services:
  db:
    image: mongo
  backend:
    image: celisapp/api-node-products
    ports:
      - 3000:3000
  frontend:
    image: celisapp/front-end-products
    ports:
      - 80:80
